%GENERO
es_sexo(ekko,masculino).
es_sexo(warwick,masculino).
es_sexo(garen,masculino).
es_sexo(lux,femenino).
es_sexo(zed,masculino).
es_sexo(katarina,femenino).
es_sexo(darius,masculino).
es_sexo(draven,masculino).
es_sexo(riven,femenino).
es_sexo(miss_fortune,femenino).
es_sexo(sona,femenino).
es_sexo(akali,femenino).
es_sexo(jarvan_iv,masculino).
es_sexo(varus,masculino).
es_sexo(ashe,femenino).
es_sexo(mordekaiser,masculino).
es_sexo(poppy,femenino).
es_sexo(teemo,masculino).
es_sexo(nunu_y_willum,masculino).
es_sexo(thresh,masculino).
es_sexo(blitzcranck,masculino).
es_sexo(tryndamere,masculino).
es_sexo(soraka,femenino).
es_sexo(twisted_fate,masculino).
es_sexo(senna,femenino).
es_sexo(lucian,masculino).
es_sexo(shen,masculino).
es_sexo(braum,masculino).
es_sexo(yasuo,masculino).


%CARRILES
es_carril(ekko,mid).
es_carril(ekko,jungla).
es_carril(warwick,jungla).
es_carril(garen,top).
es_carril(garen,mid).
es_carril(lux,mid).
es_carril(lux,soporte).
es_carril(zed,mid).
es_carril(katarina,mid).
es_carril(darius,top).
es_carril(draven,adc).
es_carril(riven,top).
es_carril(riven,jungla).
es_carril(miss_fortune,adc).
es_carril(sona,soporte).
es_carril(akali,mid).
es_carril(jarvan_iv,jungla).
es_carril(jarvan_iv,top).
es_carril(varus,adc).
es_carril(ashe,adc).
es_carril(mordekaiser,top).
es_carril(mordekaiser,mid).
es_carril(poppy,top).
es_carril(poppy,jungla).
es_carril(teemo,top).
es_carril(teemo,mid).
es_carril(teemo,jungla).
es_carril(teemo,soporte).
es_carril(teemo,adc).
es_carril(nunu_y_willum,jungla).
es_carril(thresh,soporte).
es_carril(blitzcranck,soporte).
es_carril(tryndamere,top).
es_carril(tryndamere,jungla).
es_carril(soraka,soporte).
es_carril(twisted_fate,mid).
es_carril(twisted_fate,adc).
es_carril(senna,soporte).
es_carril(senna,mid).
es_carril(senna,adc).
es_carril(lucian,adc).
es_carril(lucian,mid).
es_carril(shen,top).
es_carril(shen,soporte).
es_carril(shen,jungla).
es_carril(braum,soporte).
es_carril(yasuo,mid).
es_carril(yasuo,top).


%TIPO
es_tipo(ekko,asesino).
es_tipo(warwick,luchador).
es_tipo(garen,luchador).
es_tipo(lux,mago).
es_tipo(zed,asesino).
es_tipo(katarina,asesino).
es_tipo(darius,luchador).
es_tipo(draven,tirador).
es_tipo(riven,luchador).
es_tipo(miss_fortune,tirador).
es_tipo(sona,mago).
es_tipo(akali,asesino).
es_tipo(jarvan_iv,luchador).
es_tipo(varus,tirador).
es_tipo(ashe,tirador).
es_tipo(mordekaiser,luchador).
es_tipo(poppy,tanque).
es_tipo(teemo,tirador).
es_tipo(nunu_y_willum,tanque).
es_tipo(thresh,tanque).
es_tipo(blitzcranck,tanque).
es_tipo(tryndamere,luchador).
es_tipo(soraka,mago).
es_tipo(twisted_fate,mago).
es_tipo(senna,tirador).
es_tipo(lucian,tirador).
es_tipo(shen,tanque).
es_tipo(braum,tanque).
es_tipo(yasuo,luchador).





%ARMA
usa_arma(ekko,espada).
usa_arma(warwick,garras).
usa_arma(garen,espada).
usa_arma(lux,baculo).
usa_arma(zed,cuchilla_de_mano).
usa_arma(katarina,dagas).
usa_arma(darius,hacha).
usa_arma(draven,hacha).
usa_arma(riven,espada).
usa_arma(miss_fortune,pistola).
usa_arma(sona,instrumento_musical).
usa_arma(akali,dagas).
usa_arma(jarvan_iv,lanza).
usa_arma(varus,arco).
usa_arma(ashe,arco).
usa_arma(mordekaiser,maza).
usa_arma(poppy,martillo).
usa_arma(teemo,dardos).
usa_arma(nunu_y_willum,garras).
usa_arma(thresh,gancho).
usa_arma(blitzcranck,brazo).
usa_arma(tryndamere,espada).
usa_arma(soraka,baculo).
usa_arma(twisted_fate,cartas).
usa_arma(senna,pistola).
usa_arma(lucian,pistola).
usa_arma(shen,espada).
usa_arma(braum,escudo).
usa_arma(yasuo,espada).





%REGION
es_de_region(ekko,zaun).
es_de_region(warwick,zaun).
es_de_region(garen,demacia).
es_de_region(lux,demacia).
es_de_region(zed,jonia).
es_de_region(katarina,noxus).
es_de_region(darius,noxus).
es_de_region(draven,noxus).
es_de_region(riven,noxus).
es_de_region(miss_fortune,aguasturbias).
es_de_region(sona,demacia).
es_de_region(akali,jonia).
es_de_region(jarvan_iv,demacia).
es_de_region(varus,jonia).
es_de_region(ashe,freljord).
es_de_region(mordekaiser,islas_de_las_sombras).
es_de_region(poppy,bandle).
es_de_region(teemo,bandle).
es_de_region(nunu_y_willum,freljord).
es_de_region(thresh,islas_de_las_sombras).
es_de_region(blitzcranck,zaun).
es_de_region(tryndamere,freljord).
es_de_region(soraka,targon).
es_de_region(twisted_fate,aguasturbias).
es_de_region(senna,demacia).
es_de_region(lucian,demacia).
es_de_region(shen,jonia).
es_de_region(braum,freljord).
es_de_region(yasuo,jonia).


cargar:-exists_file('rules.pl'),consult('rules.bd').
que_personaje_es(PERSONAJE,SEXO,CARRIL,TIPO,ARMA,REGION):- es_sexo(PERSONAJE,SEXO), es_carril(PERSONAJE,CARRIL), es_tipo(PERSONAJE,TIPO), usa_arma(PERSONAJE,ARMA), es_de_region(PERSONAJE,REGION).